{-# LANGUAGE CPP, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving, MultiParamTypeClasses, ScopedTypeVariables, TypeSynonymInstances, UndecidableInstances #-}
#if !MIN_VERSION_base(4,8,0)
{-# LANGUAGE OverlappingInstances #-}
#endif

---------- GENERATED FILE, EDITS WILL BE LOST ----------

{-# LANGUAGE NoMonomorphismRestriction #-}

module Graphics.UI.Qtah.Gui.QImage (
  QImageValue (..),
  QImageConstPtr (..),
  QImagePtr (..),
  QImageConst,
  QImage,
  castConst,
  cast,
  downCastConst,
  downCast,
  decode,
  new,
  newCopy,
  newWithConstData,
  newWithConstDataAndBytesPerLine,
  newWithData,
  newWithDataAndBytesPerLine,
  newWithFile,
  newWithSize,
  newWithSizeRaw,
  aSSIGN,
  allGray,
  bitPlaneCount,
  bits,
  bitsConst,
  byteCount,
  bytesPerLine,
  color,
  colorCount,
  colorTable,
  constScanLine,
  copyRaw,
  copyRect,
  createAlphaMask,
  createHeuristicMask,
  createHeuristicMaskWithClipTight,
  createMaskFromColor,
  createMaskFromColorWithMode,
  depth,
  devicePixelRatio,
  dotsPerMeterX,
  dotsPerMeterY,
  eQ,
  fillWithColor,
  fillWithGlobalColor,
  fillWithPixel,
  format,
  fromDataByteArray,
  fromDataByteArrayWithFormat,
  fromDataRaw,
  fromDataRawWithFormat,
  hasAlphaChannel,
  height,
  invertPixels,
  invertPixelsWithMode,
  isGrayscale,
  isNull,
  load,
  loadFromDataByteArray,
  loadFromDataByteArrayWithFormat,
  loadFromDataRaw,
  loadFromDataRawWithFormat,
  loadWithFormat,
  mirrored,
  nE,
  newWithConstDataAndBytesPerLineAndCleanup,
  newWithConstDataAndCleanup,
  newWithDataAndBytesPerLineAndCleanup,
  newWithDataAndCleanup,
  newWithFileAndFormat,
  offset,
  pixelAtPoint,
  pixelAtRaw,
  pixelColorAtPoint,
  pixelColorAtRaw,
  pixelIndexAtPoint,
  pixelIndexAtRaw,
  rect,
  rgbSwapped,
  save,
  saveAll,
  scaled,
  scaledAll,
  scaledToHeight,
  scaledToHeightAll,
  scaledToWidth,
  scaledToWidthAll,
  scaledWithRaw,
  scaledWithRawAll,
  scanLine,
  scanLineConst,
  setColor,
  setColorCount,
  setColorTable,
  setDevicePixelRatio,
  setDotsPerMeterX,
  setDotsPerMeterY,
  setOffset,
  setPixelAtPoint,
  setPixelAtRaw,
  setPixelColorAtPoint,
  setPixelColorAtRaw,
  setText,
  size,
  swap,
  text,
  textKeys,
  transformedWithTransform,
  transformedWithTransformAll,
  trueMatrixWithTransform,
  validAtPoint,
  validAtRaw,
  width,
  QImageFormat (..),
  QImageInvertMode (..),
  ) where

import qualified Foreign.Hoppy.Runtime as QtahFHR
import Graphics.UI.Qtah.Generated.Gui.QImage
import qualified Graphics.UI.Qtah.Generated.Gui.QImage as M122
import Prelude ()
import qualified Prelude as QtahP


castConst = toQImageConst
cast = toQImage
downCastConst = downToQImageConst
downCast = downToQImage

decode :: (QImageConstPtr this) => this -> QtahP.IO M122.QImage
decode = QtahFHR.decode QtahP.. toQImageConst