{-# LANGUAGE CPP, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving, MultiParamTypeClasses, ScopedTypeVariables, TypeSynonymInstances, UndecidableInstances #-}
#if !MIN_VERSION_base(4,8,0)
{-# LANGUAGE OverlappingInstances #-}
#endif

---------- GENERATED FILE, EDITS WILL BE LOST ----------

{-# LANGUAGE NoMonomorphismRestriction #-}

module Graphics.UI.Qtah.Gui.QStandardItem (
  QStandardItemValue (..),
  QStandardItemConstPtr (..),
  QStandardItemPtr (..),
  QStandardItemConst,
  QStandardItem,
  castConst,
  cast,
  downCastConst,
  downCast,
  new,
  newWithIconAndText,
  newWithRows,
  newWithRowsAndColumns,
  newWithText,
  accessibleDescription,
  accessibleText,
  appendColumn,
  appendRowItem,
  appendRowItems,
  appendRows,
  background,
  checkState,
  child,
  childWithColumn,
  clone,
  column,
  columnCount,
  flags,
  font,
  foreground,
  getData,
  getDataWithRole,
  getType,
  hasChildren,
  icon,
  index,
  insertColumn,
  insertColumns,
  insertRowItem,
  insertRowItems,
  insertRowsCount,
  insertRowsItems,
  isAutoTristate,
  isCheckable,
  isDragEnabled,
  isDropEnabled,
  isEditable,
  isEnabled,
  isSelectable,
  isUserTristate,
  model,
  parent,
  removeColumn,
  removeColumns,
  removeRow,
  removeRows,
  row,
  rowCount,
  setAccessibleDescription,
  setAccessibleText,
  setAutoTristate,
  setBackground,
  setCheckState,
  setCheckable,
  setChild,
  setChildWithColumn,
  setColumnCount,
  setData,
  setDataWithRole,
  setDragEnabled,
  setDropEnabled,
  setEditable,
  setEnabled,
  setFlags,
  setFont,
  setForeground,
  setIcon,
  setRowCount,
  setSelectable,
  setSizeHint,
  setStatusTip,
  setText,
  setTextAlignment,
  setToolTip,
  setUserTristate,
  setWhatsThis,
  sizeHint,
  sortChildren,
  sortChildrenWithOrder,
  statusTip,
  takeChild,
  takeChildWithColumn,
  takeColumn,
  takeRow,
  text,
  textAlignment,
  toolTip,
  whatsThis,
  ) where

import Graphics.UI.Qtah.Generated.Gui.QStandardItem
import Prelude ()


castConst = toQStandardItemConst
cast = toQStandardItem
downCastConst = downToQStandardItemConst
downCast = downToQStandardItem