{-# LANGUAGE CPP, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving, MultiParamTypeClasses, ScopedTypeVariables, TypeSynonymInstances, UndecidableInstances #-}
#if !MIN_VERSION_base(4,8,0)
{-# LANGUAGE OverlappingInstances #-}
#endif

---------- GENERATED FILE, EDITS WILL BE LOST ----------

{-# LANGUAGE NoMonomorphismRestriction #-}

module Graphics.UI.Qtah.Core.Types (
  QReal,
  QtAlignmentFlag (..),
  QtAlignment,
  fromQtAlignment,
  IsQtAlignment (..),
  alignLeft,
  alignRight,
  alignHCenter,
  alignJustify,
  alignTop,
  alignBottom,
  alignVCenter,
  alignAbsolute,
  QtAspectRatioMode (..),
  QtBrushStyle (..),
  QtCaseSensitivity (..),
  QtCheckState (..),
  QtContextMenuPolicy (..),
  QtCorner (..),
  QtCursorMoveStyle (..),
  QtDropAction (..),
  QtDropActions,
  fromQtDropActions,
  IsQtDropActions (..),
  ignoreAction,
  copyAction,
  moveAction,
  linkAction,
  actionMask,
  targetMoveAction,
  QtEventPriority (..),
  QtFillRule (..),
  QtFocusReason (..),
  QtGlobalColor (..),
  QtImageConversionFlag (..),
  QtImageConversionFlags,
  fromQtImageConversionFlags,
  IsQtImageConversionFlags (..),
  auto,
  colorOnly,
  monoOnly,
  orderedDither,
  thresholdDither,
  orderedAlphaDither,
  diffuseAlphaDither,
  preferDither,
  avoidDither,
  noOpaqueDetection,
  noFormatConversion,
  QtInputMethodHint (..),
  QtInputMethodHints,
  fromQtInputMethodHints,
  IsQtInputMethodHints (..),
  imhNone,
  imhHiddenText,
  imhSensitiveData,
  imhNoAutoUppercase,
  imhPreferNumbers,
  imhPreferUppercase,
  imhPreferLowercase,
  imhNoPredictiveText,
  imhDate,
  imhTime,
  imhPreferLatin,
  imhMultiLine,
  imhDigitsOnly,
  imhFormattedNumbersOnly,
  imhUppercaseOnly,
  imhLowercaseOnly,
  imhDialableCharactersOnly,
  imhEmailCharactersOnly,
  imhUrlCharactersOnly,
  imhLatinOnly,
  imhExclusiveInputMask,
  QtItemDataRole (..),
  QtItemFlag (..),
  QtItemFlags,
  fromQtItemFlags,
  IsQtItemFlags (..),
  noItemFlags,
  itemIsSelectable,
  itemIsEditable,
  itemIsDragEnabled,
  itemIsDropEnabled,
  itemIsUserCheckable,
  itemIsEnabled,
  itemIsAutoTristate,
  itemNeverHasChildren,
  itemIsUserTristate,
  QtKey (..),
  QtKeyboardModifier (..),
  QtKeyboardModifiers,
  fromQtKeyboardModifiers,
  IsQtKeyboardModifiers (..),
  noModifier,
  shiftModifier,
  controlModifier,
  altModifier,
  metaModifier,
  keypadModifier,
  groupSwitchModifier,
  QtLayoutDirection (..),
  QtMaskMode (..),
  QtMatchFlag (..),
  QtMatchFlags,
  fromQtMatchFlags,
  IsQtMatchFlags (..),
  matchExactly,
  matchFixedString,
  matchContains,
  matchStartsWith,
  matchEndsWith,
  matchCaseSensitive,
  matchRegExp,
  matchWildcard,
  matchWrap,
  matchRecursive,
  QtMouseButton (..),
  QtMouseButtons,
  fromQtMouseButtons,
  IsQtMouseButtons (..),
  noButton,
  allButtons,
  leftButton,
  rightButton,
  middleButton,
  QtMouseEventFlag (..),
  QtMouseEventFlags,
  fromQtMouseEventFlags,
  IsQtMouseEventFlags (..),
  mouseEventCreatedDoubleClick,
  QtMouseEventSource (..),
  QtNavigationMode (..),
  QtOrientation (..),
  QtOrientations,
  fromQtOrientations,
  IsQtOrientations (..),
  horizontal,
  vertical,
  QtScreenOrientation (..),
  QtScreenOrientations,
  fromQtScreenOrientations,
  IsQtScreenOrientations (..),
  primaryOrientation,
  portraitOrientation,
  landscapeOrientation,
  invertedPortraitOrientation,
  invertedLandscapeOrientation,
  QtScrollBarPolicy (..),
  QtScrollPhase (..),
  QtSortOrder (..),
  QtTextElideMode (..),
  QtTextFormat (..),
  QtTextInteractionFlag (..),
  QtTextInteractionFlags,
  fromQtTextInteractionFlags,
  IsQtTextInteractionFlags (..),
  noTextInteraction,
  textSelectableByMouse,
  textSelectableByKeyboard,
  linksAccessibleByMouse,
  linksAccessibleByKeyboard,
  textEditable,
  textEditorInteraction,
  textBrowserInteraction,
  QtToolBarArea (..),
  QtToolBarAreas,
  fromQtToolBarAreas,
  IsQtToolBarAreas (..),
  noToolBarArea,
  leftToolBarArea,
  rightToolBarArea,
  topToolBarArea,
  bottomToolBarArea,
  allToolBarAreas,
  QtToolButtonStyle (..),
  QtTransformationMode (..),
  QtWindowModality (..),
  QtWindowState (..),
  QtWindowStates,
  fromQtWindowStates,
  IsQtWindowStates (..),
  windowNoState,
  windowMinimized,
  windowMaximized,
  windowFullScreen,
  windowActive,
  QtWindowType (..),
  QtWindowFlags,
  fromQtWindowFlags,
  IsQtWindowFlags (..),
  widget,
  window,
  dialog,
  sheet,
  drawer,
  popup,
  tool,
  toolTip,
  splashScreen,
  desktop,
  subWindow,
  foreignWindow,
  coverWindow,
  ) where

import Graphics.UI.Qtah.Generated.Core.Types
import Prelude ()
import qualified Prelude as QtahP


type QReal = QtahP.Double